version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
  name: RazorEngine
deploy:
- provider: NuGet
  api_key:
    secure: vrjQEmz+4Zs/dYOyNWP76UtIkmxD99i0JmvDt/bkLjSg06fCbbT2Q9BiuHBABe8L
  artifact: /.*\.nupkg/